CREATE SCHEMA DB_DATTA;

USE DB_DATTA;

CREATE TABLE restaurant (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    RESTAURANT_NAME VARCHAR(255) NOT NULL,
    RESTAURANT_ADDRESS VARCHAR(255),
    CITY VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE permission (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PERMISSION_NAME VARCHAR(255) NOT NULL,
    PERMISSION_DESCRIPTION TEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE plan (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PLAN_NAME VARCHAR(255) NOT NULL,
    PLAN_DESCRIPTION TEXT NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE NFT_TIER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TIER_NAME VARCHAR(255),
    TIER_DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE user (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(255),
    CREATION_DATE DATETIME,
    CRYPTO_ADDRESS VARCHAR(255),
    PRIMARY KEY (ID),
    UNIQUE KEY (CRYPTO_ADDRESS)
);

CREATE TABLE NFT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NFT_NAME VARCHAR(255) NOT NULL,
    NFT_TIER VARCHAR(255) NOT NULL,
    NFT_COLLECTION VARCHAR(255) NOT NULL,
    NFT_IMAGE BLOB,
    NFT_DNA TEXT,
    NFT_DATE DATETIME,
    NFT_EDITION TINYINT,
    CREATION_DATE DATETIME,
    USER_ID BIGINT,
    NFT_TIER_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID)
        REFERENCES USER (ID),
    FOREIGN KEY (NFT_TIER_ID)
        REFERENCES NFT_TIER (ID)
);

CREATE TABLE user_restaurant (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT,
    RESTAURANT_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID)
        REFERENCES USER (ID),
    FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANT (ID)
);

CREATE TABLE permission_NFT_TIER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PERMISSION_ID BIGINT,
    NFT_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSION (ID),
    FOREIGN KEY (NFT_ID)
        REFERENCES NFT_TIER (ID)
);

CREATE TABLE plan_permission (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PLAN_ID BIGINT,
    PERMISSION_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSION (ID),
    FOREIGN KEY (PLAN_ID)
        REFERENCES PLAN (ID)
);

CREATE TABLE restaurant_permission (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    RESTAURANT_ID BIGINT,
    PERMISSION_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSION (ID),
    FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANT (ID)
);

